# Generated by Django 4.2.3 on 2023-10-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_employee_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
