# Generated by Django 4.2.3 on 2023-10-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_employee_email_alter_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
