# Generated by Django 4.2.3 on 2023-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_employee_email_remove_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
