# Generated by Django 4.2.3 on 2023-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_employee_designation_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
