# Generated by Django 5.1.1 on 2024-09-21 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('assigned', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
            ],
        ),
    ]
